FairlyRepair/FairlyRepair/Areas/Admin/Controllers/AuditAdminController.cs
using AutoMapper;
using FairlyRepair.ActionFilters;
using FairlyRepair.Areas.Admin.ViewModels.Audit;
using FairlyRepair.Models;
using FairlyRepair.Models.Others;
using FairlyRepair.Repositories;
using FairlyRepair.Utility.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FairlyRepair.Areas.Admin.Controllers
{
    [Authorize]
    //[ErrorHandleAdminActionFilter]
    public class AuditAdminController : BaseAdminController
    {
        // GET: Admin/AuditAdmin
        private AdminRepository adminRepository = new AdminRepository(new FairlyRepairDBEntities());
        private AuditRepository auditRepository = new AuditRepository(new FairlyRepairDBEntities());
        private Repositories.MeetRepositories.AuditLevelRepository auditLevelRepository = new Repositories.MeetRepositories.AuditLevelRepository(new MeetModels.MeetingSignInDBEntities());
        private EightDRepository eightDRepository = new EightDRepository(new FairlyRepairDBEntities());
        private Repositories.T8Repositories.PersonRepository t8personRepository = new Repositories.T8Repositories.PersonRepository(new T8ERPEntities());

        // GET: Admin/AuditAdmin
        public ActionResult Index(AuditIndexView model)
        {
            var adminInfo = AdminInfoHelper.GetAdminInfo();
            switch ((MeetAdminType)adminInfo.AccountType)
            {
                case MeetAdminType.Employee:
                    return RedirectToAction("Index", "EightDAdmin");              
            }
            
            //var personInfo = t8personRepository.FindByJobID(adminRepository.GetById(adminInfo.ID).Account);
            //var personDept = personInfo == null ? "" : personInfo.DeptID;
            string officerId = model.State == null ? "" : adminInfo.Account;
            
            var query = auditRepository.Query(model.IsInvalid, model.ReportID, model.Type, model.State, model.Title, model.PersonID, officerId);
            if (!model.IsOfficer)
            {
                query = query.Where(q => q.Officer != adminInfo.Account);
            }

            List<string> auditDepts = new List<string>();
            if (adminInfo.AccountType == (int)MeetAdminType.Manager)
            {//主管審核
                auditDepts = auditLevelRepository.Query(true, "", "", adminInfo.Account).Select(q => q.DeptId).ToList();
            }
            else if (adminInfo.AccountType == (int)MeetAdminType.Vice)
            {//副總審核
                auditDepts = auditLevelRepository.Query(true, "", adminInfo.Account, "").Select(q => q.DeptId).ToList();
            }
            else if (adminInfo.AccountType == (int)MeetAdminType.President)
            {//總經理審核
                auditDepts = auditLevelRepository.Query(true, adminInfo.Account, "", "").Select(q => q.DeptId).ToList();
            }
            var sameDeptPersonIdList = t8personRepository.GetPersonQuery("", "").Where(q => auditDepts.Contains(q.DeptID)).Select(q => q.JobID).ToList();
            var adminAccList = adminRepository.GetAll().Where(q => sameDeptPersonIdList.Contains(q.Account)).Select(q => q.Account).ToList();
            query = query.Where(q => sameDeptPersonIdList.Contains(q.PersonID) || adminAccList.Contains(q.Officer));

            var pageResult = query.ToPageResult<Audit>(model);
            model.PageResult = Mapper.Map<PageResult<AuditItemView>>(pageResult);

            Repositories.MeetRepositories.AdminRepository meetAdminRepository = new Repositories.MeetRepositories.AdminRepository(new MeetModels.MeetingSignInDBEntities());
            foreach (var item in model.PageResult.Data)
            {
                item.Title = "";
                try
                {
                    var officer = meetAdminRepository.GetByAccount(item.Officer);
                    string officerStr = officer == null || string.IsNullOrEmpty(officer.Name) ? officer.Account : officer.Name;
                    item.OfficerName = " 【填表人 : " + officerStr + "】";

                    var reportData = eightDRepository.GetById(item.ReportID);
                    if (reportData != null)
                    {
                        item.Title = reportData.Title;
                    }

                }
                catch (Exception ex)
                {
                    item.Title = "找不到標題";
                    item.OfficerName = "";
                }
                //if (item.Type > (int)AuditType.Internal)
                //{
                //    var personInfo = t8personRepository.FindByJobID(item.PersonID);
                //    if (personInfo != null)
                //    {
                //        item.PersonName = "【" + personInfo.DepartmentStr + "】";
                //        item.PersonName += personInfo.Name;
                //    }
                //}
                //else
                //{
                //    var officerAdminInfo = adminRepository.GetById(item.Officer);
                //    var officerPersonInfo = t8personRepository.FindByJobID(officerAdminInfo.Account);
                //    item.OfficerName = officerPersonInfo == null ? officerAdminInfo.Name : officerPersonInfo.Name;
                //}
            }

            return View(model);
        }
        
        //public ActionResult Add(int id, int type)
        //{
        //    if (id == 0 || type == 0)
        //    {
        //        return RedirectToAction("Index", "AuditIndex");
        //    }
        //    //新增待審資料
        //    var data = new Audit() {
        //        TargetID = id,
        //        Type = type,
        //        State = (int)AuditState.OfficerAudit,
        //        IsInvalid = false,
        //        Officer = "",
        //        CreateDate= DateTime.Now
        //    };
        //    auditRepository.Insert(data);

        //    return RedirectToAction("Index", "AuditIndex");
        //}
    }
}

FairlyRepair/FairlyRepair/Areas/Admin/Views/AuditAdmin/Index.cshtml
@model FairlyRepair.Areas.Admin.ViewModels.Audit.AuditIndexView

<section class="content-header">
    <h1>
        簽核管理
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index", "HomeAdmin")"><i class="fa fa-home"></i> 首頁</a></li>
        <li class="active">簽核管理</li>
    </ol>
</section>

<section class="content">
        <div class="row">
            <!--搜尋條件-->
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">搜尋</h3>
                        <div class="box-tools">
                            <button type="button" class="btn btn-tool" data-box-widget="collapse">
                                <i class="fa fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    @using (Html.BeginForm("Index", "AuditAdmin", FormMethod.Get, new { @class = "form-horizontal" }))
                    {
                        @*@Html.HiddenFor(model => model.State)*@
                        @Html.HiddenFor(model => model.PersonID)
                        <div class="box-body">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Title, new { @class = "col-sm-2 control-label" })
                                <div class="col-sm-10">
                                    @Html.TextBoxFor(model => model.Title, new { @class = "form-control", @placeholder = "標題" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Type, new { @class = "col-sm-2 control-label" })
                                <div class="col-sm-4">
                                    @Html.DropDownListFor(model => model.Type, Model.TypeOptions, "---全部---", new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.State, new { @class = "col-sm-2 control-label" })
                                <div class="col-sm-4">
                                    @Html.DropDownListFor(model => model.State, Model.StateOptions, "---全部---", new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.IsInvalid, new { @class = "col-sm-2 control-label" })
                                <div class="col-sm-4">
                                    @Html.EditorFor(model => model.IsInvalid, "UseStatusDropDownList", new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">顯示承辦資料</label>
                                <div class="col-sm-4">
                                    <div class="form-check pretty p-switch p-fill" style="margin-bottom: 10px; padding-top: 10px; padding-left:0px;">
                                        @Html.CheckBoxFor(model => model.IsOfficer, new { @class = "form-check-input lock_switch" })
                                        <div class="state p-success">
                                            @Html.LabelFor(model => model.IsOfficer, new { @class = "form-check-label", @style = "font-weight:bold; " })
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-info">搜尋</button>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>

</section>
<section class="content">

        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">簽核列表</h3>
                    </div>
                    <div class="box-body">
                        <div id="dataList_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                            @Html.Partial("_PageSizeAdmin", Model.PageResult)
                            <div class="row">
                                <div class="col-sm-12 table-responsive">
                                    <table class="table table-bordered table-hover dataTable">
                                        <thead>
                                            <tr>
                                                <th>
                                                    @Html.DisplayNameFor(x => x.ID)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(x => x.Title)
                                                </th>
                                                <th>
                                                    填表人員
                                                </th>
                                                @*<th data-sorting="Type">
                                                    @Html.DisplayNameFor(x => x.Type)
                                                </th>*@
                                                <th data-sorting="State">
                                                    @Html.DisplayNameFor(x => x.State)
                                                </th>
                                                <th data-sorting="IsInvalid">
                                                    @Html.DisplayNameFor(x => x.IsInvalid)
                                                </th>
                                                <th data-sorting="CreateDate">
                                                    @Html.DisplayNameFor(x => x.CreateDate)
                                                </th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model.PageResult.Data)
                                            {
                                                string typeStr = item.Type.ToString();
                                                string stateStr = item.State.ToString();
                                                string editUrl = "";
                                                switch (item.Type)
                                                {
                                                    case 1://8D
                                                        editUrl = "/Admin/EightDAdmin/Edit?id=" + item.ReportID + "&FromAudit=True";
                                                        break;
                                                }
                                                <tr>
                                                    <td>
                                                        @item.ID
                                                    </td>
                                                    <td>
                                                        @item.Title
                                                    </td>
                                                    <td>
                                                        <label class="label bg-teal">@item.OfficerName</label>
                                                    </td>
                                                    @*<td>
                                                        @Html.DisplayFor(model => item.Type, "_AuditTypeStatus")
                                                    </td>*@
                                                    <td>
                                                        @Html.DisplayFor(model => item.State, "_AuditStateStatus")
                                                    </td>
                                                    <td>
                                                        @if (item.IsInvalid)
                                                        {
                                                            <span class="label label-danger">駁回</span>
                                                        }
                                                    </td>
                                                    <th>
                                                        @item.CreateDate.ToString("yyyy/MM/dd")
                                                    </th>
                                                    <td>
                                                        <a class="btn btn-primary" href="@editUrl">查看</a>
                                                        @*@Html.ActionLink("查看", editAction, editController, new { id = item.ID }, new { @class = "btn btn-primary" })*@
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th>
                                                    @Html.DisplayNameFor(x => x.ID)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(x => x.Title)
                                                </th>
                                                <th>
                                                    填表人員
                                                </th>
                                                @*<th>
                                                    @Html.DisplayNameFor(x => x.Type)
                                                </th>*@
                                                <th>
                                                    @Html.DisplayNameFor(x => x.State)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(x => x.IsInvalid)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(x => x.CreateDate)
                                                </th>
                                                <th></th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                            @Html.Partial("_PageAdmin", Model.PageResult)
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>

@section scripts{
    <script src="~/Scripts/Admin/page.js"></script>
}