FairlyRepair/FairlyRepair/Areas/Admin/Controllers/EightDAdminController.cs
using AutoMapper;
using FairlyRepair.ActionFilters;
using FairlyRepair.Areas.Admin.ViewModels.EightD;
using FairlyRepair.Models;
using FairlyRepair.MeetModels;
using FairlyRepair.Models.Others;
using FairlyRepair.Repositories;
using FairlyRepair.Utility.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using FairlyRepair.Utility;
using System.Text;

namespace FairlyRepair.Areas.Admin.Controllers
{
    [Authorize]
    //[ErrorHandleAdminActionFilter]
    public class EightDAdminController : BaseAdminController
    {
        private EightDRepository eightDRepository = new EightDRepository(new FairlyRepairDBEntities());
        private EightDFileRepository eightDFileRepository = new EightDFileRepository(new FairlyRepairDBEntities());
        private EightDCategoryRepository eightDCategoryRepository = new EightDCategoryRepository(new FairlyRepairDBEntities());
        private AuditRepository auditRepository = new AuditRepository(new FairlyRepairDBEntities());      
        private AdminRepository adminRepository = new AdminRepository(new FairlyRepairDBEntities());      
        private Repositories.MeetRepositories.AuditLevelRepository auditLevelRepository = new Repositories.MeetRepositories.AuditLevelRepository(new MeetingSignInDBEntities());
        private Repositories.T8Repositories.PersonRepository t8personRepository = new Repositories.T8Repositories.PersonRepository(new T8ERPEntities());

        public int AuditProcessing = (int)FormAudit.Processing;
        public int AuditApproval = (int)FormAudit.Approval;
        public int AuditReject = (int)FormAudit.Reject;

        // GET: Admin/EightDAdmin

        public ActionResult OverView()
        {
            Repositories.T8Repositories.DepartmentRepository t8departmentRepository = new Repositories.T8Repositories.DepartmentRepository(new T8ERPEntities());
            OverViewView model = new OverViewView();
            model.StartDate = Convert.ToDateTime("2020/01/01");
            model.EndDate = DateTime.Now;

            return View(model);
        }

        public ActionResult Index(EightDIndexView model)
        {
            var adminInfo = AdminInfoHelper.GetAdminInfo();
            model.Category = 0;
            if (!string.IsNullOrEmpty(model.CategoryStr))
            {
                var cateData = eightDCategoryRepository.FindByTitle(model.CategoryStr);
                model.Category = cateData == null ? 0 : cateData.ID;
            }
            var query = eightDRepository.Query(model.IsFinished, model.Title, model.Category, model.Customer, model.Depts, false);
            var pageResult = query.ToPageResult<Models.EightD>(model);
            model.PageResult = Mapper.Map<PageResult<EightDView>>(pageResult);

            foreach (var item in model.PageResult.Data)
            {
                #region 審核狀態
                var auditInfo = auditRepository.Query(null, item.ID, 0, null, "", "").Where(q => q.Type == (int)AuditType.EightD).OrderByDescending(q => q.ID).FirstOrDefault();
                 if (auditInfo == null)
                {
                    item.AuditStatus = "已填寫未送審";
                    item.IsInvalid = false;
                }
                else
                {
                    item.AuditState = auditInfo == null ? 0 : auditInfo.State;
                    item.AuditStatus = EnumHelper.GetDescription((AuditState)item.AuditState);
                    item.IsInvalid = auditInfo == null ? false : auditInfo.IsInvalid;
                }
                #endregion
            }

            return View(model);
        }

        public ActionResult Edit(int id = 0, bool isNew = false, bool FromAudit = false)
        {
            var adminInfo = AdminInfoHelper.GetAdminInfo();

            EightDView model = new EightDView();
            if (id == 0)
            {
                model = new EightDView();
                model.CreaterId = adminInfo.Account;
            }
            else
            {
                var query = eightDRepository.GetById(id);
                model = Mapper.Map<EightDView>(query);
                model.FilesList = eightDFileRepository.Query(id).ToList();

                if (model == null)
                {
                    ShowMessage(false, "找不到資料");
                    return RedirectToAction("Index");
                }

                if (isNew && model.IsAudit)
                {//取消送審/重新編輯
                    var newData = Mapper.Map<EightDView>(query);
                    query.IsRevoke = true;
                    eightDRepository.Update(query);
                    var oldAudit = auditRepository.Query(null, query.ID, (int)AuditType.EightD, null, "", "").FirstOrDefault();
                    if (oldAudit != null)//複製並更新舊的審核紀錄
                    {
                        //撤銷舊資料
                        oldAudit.IsInvalid = true;
                        auditRepository.Update(oldAudit);

                        //重置審核資料
                        newData.AuditInfo = model.AuditInfo = auditRepository.FindByTarget(query.ID, (int)AuditType.EightD);
                    }
                    EightD data = Mapper.Map<EightD>(newData);
                    data.IsAudit = false;
                    data.OfficerAudit = AuditProcessing;
                    data.OfficerRemark = "";
                    data.OfficerSignature = "";
                    data.OfficerAuditDate = null;
                    data.ManagerAudit = AuditProcessing;
                    data.ManagerRemark = "";
                    data.ManagerSignature = "";
                    data.ManagerAuditDate = null;
                    data.ViceAudit = AuditProcessing;
                    data.ViceRemark = "";
                    data.ViceSignature = "";
                    data.ViceAuditDate = null;
                    data.PresidentAudit = AuditProcessing;
                    data.PresidentRemark = "";
                    data.PresidentSignature = "";
                    data.PresidentAuditDate = null;
                    newData.ID = eightDRepository.Insert(data);
                    newData = Mapper.Map<EightDView>(eightDRepository.GetById(newData.ID));

                    SetEightDViewData(FromAudit, newData);

                    return RedirectToAction("Edit", new { id = newData.ID, FromAudit = FromAudit});
                }
            }
            SetEightDViewData(FromAudit, model);

            return View(model);
        }

        private void SetEightDViewData(bool FromAudit, EightDView model)
        {
            model.FromAudit = FromAudit;

            var officerPersonInfo = t8personRepository.FindByJobID(model.CreaterId);
            if (officerPersonInfo != null)
            {
                model.OfficerDeptId = officerPersonInfo.DeptID;
                model.OfficerDeptName = officerPersonInfo.DepartmentStr;
                model.OfficerName = officerPersonInfo.Name;

                var auditLevelData = auditLevelRepository.FindByDept(officerPersonInfo.DeptID);
                model.AuditLevelInfo = auditLevelData;
                //主管
                if (model.ManagerAudit > 1)
                {
                    model.ManagerSignature = auditLevelData.ManagerReview + ".jpg";
                    var personInfo = t8personRepository.FindByJobID(auditLevelData.ManagerReview);
                    model.ManagerDeptId = personInfo.DeptId;
                    model.ManagerDeptName = personInfo.DepartmentStr;
                    model.ManagerName = personInfo.Name;
                }
                //副總
                if (model.ViceAudit > 1)
                {
                    model.ViceSignature = auditLevelData.ViceReview + ".jpg";
                    var personInfo = t8personRepository.FindByJobID(auditLevelData.ViceReview);
                    model.ViceDeptId = personInfo.DeptId;
                    model.ViceDeptName = personInfo.DepartmentStr;
                    model.ViceName = personInfo.Name;
                }
                //總經理
                if (model.PresidentAudit > 1)
                {
                    model.PresidentSignature = auditLevelData.PresidentReview + ".jpg";
                    var personInfo = t8personRepository.FindByJobID(auditLevelData.PresidentReview);
                    model.PresidentDeptId = personInfo.DeptId;
                    model.PresidentDeptName = personInfo.DepartmentStr;
                    model.PresidentName = personInfo.Name;
                }
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(EightDView model)
        {
            if (model.FinishDate < Convert.ToDateTime("2000/01/01"));
            {
                model.FinishDate = null;
            }
            if (ModelState.IsValid)
            {
                try
                {
                    var adminInfo = AdminInfoHelper.GetAdminInfo();

                    //#region 檔案處理
                    //bool hasFile = ImageHelper.CheckFileExists(model.ReportFilePost);
                    //if (hasFile)
                    //{//檔案
                    //    ImageHelper.DeleteFile(PhotoFolder, model.ReportFile);
                    //    model.ReportFile = ImageHelper.SaveFile(model.ReportFilePost, PhotoFolder, model.ReportFilePost.FileName.Split('.')[0] + "_" + DateTime.Now.ToString("yyyyMMddHHmm"));
                    //}
                    //#endregion

                    EightD data = Mapper.Map<EightD>(model);

                    if (model.IsAudit)
                    {
                        data.OfficerAudit = (int)FormAudit.Approval;
                    }

                    #region 日期處理
                    data.OfficerAuditDate = SetAuditDate(data.OfficerAudit, data.OfficerAuditDate);
                    data.ManagerAuditDate = SetAuditDate(data.ManagerAudit, data.ManagerAuditDate);

FairlyRepair/FairlyRepair/Areas/Admin/Views/EightDAdmin/Index.cshtml
@model FairlyRepair.Areas.Admin.ViewModels.EightD.EightDIndexView
@{
    ViewBag.Title = "Index";
    var adminInfo = FairlyRepair.Utility.Helpers.AdminInfoHelper.GetAdminInfo();
}

<section class="content-header">
    <h1>
        8D管理
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index", "HomeAdmin")"><i class="fa fa-home"></i> 首頁</a></li>
        <li class="active">8D管理</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">搜尋</h3>
                </div>
                <div class="box-body">
                    @using (Html.BeginForm("Index", "EightDAdmin", FormMethod.Get, new { @class = "form-horizontal" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(model => model.Category)

                        <div class="form-group">
                            @Html.LabelFor(model => model.Title, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Customer, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-10">
                                @Html.DropDownListFor(model => model.Customer, Model.CustomerOptions, "---課別---", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Category, new { @class = "col-sm-2 control-label" })
                            @*<div class="col-sm-10">
                                <div class="input-group input-group-lg">
                                @Html.DropDownListFor(model => model.Category, Model.CategoryOptions, "---類別---", new { @class = "form-control" })
                                </div>
                            </div>*@
                            <div class="col-sm-10">
                                <input type="text" class="form-control" list="CategoryStr">
                                <datalist id="CategoryStr">
                                    @foreach (var item in Model.CategoryOptions.ToList())
                                    {
                                         <option>@item.Text</option>
                                    }
                                </datalist>
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Depts, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-10">
                                @foreach (var item in Model.DeptOptions)
                                {
                                    <div class="js-signer-Dept btn btn-outline-info" id="dept_@item.Value" style="margin: 2px 5px; background-color: #fff; color: #89654f; border: 2px #a97d63 solid; ">@item.Text</div>
                                }
                                <br />
                                @Html.TextBoxFor(model => model.Depts, new Dictionary<string, object> { { "data-role", "tagsinput" }, { "class", "js-dept form-control" } })
                                @*@Html.TextBoxFor(model => model.Depts, new { @class = "form-control" })*@
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.IsFinished, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(model => model.IsFinished, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-info">搜尋</button>
                                @Html.ActionLink("新增8D報告", "Edit", null, new { @class = "btn btn-primary" })
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

<section class="content">

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">8D列表</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div id="dataList_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                        @Html.Partial("_PageSizeAdmin", Model.PageResult)
                        <div class="row">
                            <div class="col-sm-12 table-responsive">
                                <table class="table table-bordered table-hover dataTable">
                                    <thead>
                                        <tr>
                                            <th>@Html.DisplayNameFor(x => x.Title)</th>
                                            <th>@Html.DisplayNameFor(x => x.Customer)</th>
                                            <th>@Html.DisplayNameFor(x => x.Category)</th>
                                            <th>@Html.DisplayNameFor(x => x.Depts)</th>
                                            <th>@Html.DisplayNameFor(x => x.IsFinished)</th>
                                            <th>@Html.DisplayNameFor(x => x.FinishDate)</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.PageResult.Data)
                                        {
                                            <tr>
                                                <td>
                                                    @if (item.IsInvalid)
                                                    {
                                                        <label class="label label-danger" style="margin-left:3px; margin-top:3px;">已駁回</label>
                                                    }
                                                    else
                                                    {
                                                        if (item.AuditState == (int)FairlyRepair.Models.AuditState.PresidentAudit)
                                                        {
                                                            <label class="label label-success" style="margin-left:3px; margin-top:3px;">已核准</label>
                                                            <br />
                                                        }
                                                        @Html.DisplayFor(model => item.AuditStatus, "_ParticipateStateStatus")
                                                        <br />
                                                    }
                                                    @item.Title
                                                </td>
                                                <td>@item.CustomerOptions.Where(q => q.Value == item.Customer.ToString()).FirstOrDefault().Text</td>
                                                <td>@item.CategoryOptions.Where(q => q.Value == item.Category.ToString()).FirstOrDefault().Text</td>
                                                <td>@item.Depts</td>
                                                <td>@Html.DisplayFor(model => item.IsFinished, "_UseStatus")</td>
                                                <td style="font-weight:bold;">
                                                    @if (item.FinishDate != null)
                                                    {
                                                        <span>@Convert.ToDateTime(item.FinishDate).ToString("yyyy/MM/dd HH:mm")</span>
                                                    }
                                                    else
                                                    {
                                                        <span>尚未結案</span>
                                                    }
                                                </td>
                                                <td>
                                                    @if (adminInfo.Account == item.CreaterId || adminInfo.AccountType < (int)FairlyRepair.Models.MeetAdminType.Employee)
                                                    {
                                                        if (adminInfo.Account == item.CreaterId)
                                                        {
                                                            <a href="@Url.Action("Edit", "EightDAdmin", new { id = item.ID })" class="btn btn-info" style="margin-bottom:3px;">
                                                                <i class="fa fa-edit">編輯</i>
                                                            </a>
                                                            <a href="@Url.Action("Delete", "EightDAdmin", new { id = item.ID })" class="btn btn-danger js-delete-confirm">
                                                                <i class="fa fa-trash">刪除</i>
                                                            </a>
                                                        }
                                                        else
                                                        {
                                                            <a href="@Url.Action("Edit", "EightDAdmin", new { id = item.ID })" class="btn btn-primary" style="margin-bottom:3px;">
                                                                <i class="fa fa-edit">查看</i>
                                                            </a>
                                                        }
                                                    }
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th>@Html.DisplayNameFor(x => x.Title)</th>
                                            <th>@Html.DisplayNameFor(x => x.Customer)</th>
                                            <th>@Html.DisplayNameFor(x => x.Category)</th>
                                            <th>@Html.DisplayNameFor(x => x.Depts)</th>
                                            <th>@Html.DisplayNameFor(x => x.IsFinished)</th>
                                            <th>@Html.DisplayNameFor(x => x.FinishDate)</th>
                                            <th></th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                        @Html.Partial("_PageAdmin", Model.PageResult)
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    <!--autocomplete-->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script>
        $(function () {
            var $selectedDeptType = $('#Depts');
            var remove;

            //Dept
            $selectedDeptType.on('itemAdded', function (event) {
                if (remove) {
                    $selectedSigner.tagsinput('remove', remove);
                    remove = '';
                }
            });
            $('.js-signer-Dept').on('click', function () {
                var id = $(this).val();
                var val = $(this).text();
                $selectedDeptType.tagsinput('add', val);
            });

            //autocomplete
            $('#jsCategory').on("focus", function () {
                $(this).autocomplete({
                    select: function (event, ui) {
                        var tagval = ui.item.value;
                        //$('#newTag_' + Id).text(tagval);
                        //$('#newTag_' + Id).val(tagval);
                    },
                    source: function (request, response) {
                        $.ajax({
                            url: "@Url.Action("GetCategory", "EightDCategoryAdmin")",
                            type: 'POST',
                            dataType: "json",
                            data: {
                                key: request.term
                            },
                            success: function (data) {
                                response($.map(data, function (item) {
                                    return {
                                        label: item.label,      //自動完成列表的顯示文字
                                        value: item.value,     //如果jSon字串中有value的值
                                    }
                                }));

                            }
                        });
                    },
                    minLength: 1,
                });
            })
        })
    </script>
}